name: CI

on:
  push:
    branches:
      - feature/actions-bis
      - master
      - release/*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v1.0.0

      - name: Set up Node.js
        uses: actions/setup-node@v1.2.0
        with:
          node-version: '10.x'

      - name: install dependencies
        run: yarn install

      - name: Check assets
        run: |
          cd src
          ls ./assets/styleguide/js
          cd ../

      - name: build qa
        run: yarn run build:qa

      - name: Commit qa build
        uses: EndBug/add-and-commit@v2.1.0
        with:
          message: "Build for qa"
          path: qa
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build production
        run: yarn run build

      - name: Commit production build
        uses: EndBug/add-and-commit@v2.1.0
        with:
          message: "Build for production"
          path: dist
          force: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
